(cl:in-package #:common-lisp-user)

(defpackage #:cleavir-bir-transformations
  (:use #:cl)
  (:local-nicknames (#:bir #:cleavir-bir)
                    (#:set #:cleavir-set)
                    (#:ctype #:cleavir-ctype)
                    (#:attributes #:cleavir-attributes)
                    (#:lambda-list #:cleavir-lambda-list))
  (:export #:module-eliminate-catches #:eliminate-catches)
  (:export #:module-optimize-variables #:function-optimize-variables)
  (:export #:simple-unwinding-p)
  (:export #:find-module-local-calls #:maybe-interpolate)
  (:export #:determine-function-environments)
  (:export #:determine-closure-extents)
  (:export #:determine-variable-extents)
  (:export #:meta-evaluate-module #:transform-call #:derive-return-type)
  (:export #:module-generate-type-checks))
